### ISSUE TITLE
Debug command simplification

### ISSUE THREAD

**Issue by LemADEC** [SimonFlash/CmdCalendar#2]
As of CmdCalendar-mc1.10.2-1.0.0.jar,
the debug command seems a bit overcomplicated:
1- reload configuration is usually done with "/<pluginName> reload"
instead here we need to type "/<pluginName debug loadConfig confirm"

2- when typing a debug command without the final confirm keyword, only errors are reported.
There's no warning or details provided that would justify typing the command without the confirm keyword. I would suggest to remove that keyword altogether.

3- as an admin, I expect configuration to be saved whenever I change task. Maybe with a few seconds delay to avoid lag when using scripts. For sure, I don't expect having to type "/cmdcal debug SaveConfig confirm" whenever I change something. It's counter-intuitive compared to usual plugins behavior.

**Comment by SimonFlash** [comment]
1: Most plugins do not have long-term features running, while CmdCalendar is *entirely* about running tasks. Reloading the config could de-sync the task list and running tasks, and is something that should only be done as a last resort.
2: This is due to improper class inheritance and has been fixed. Warnings such as the above are provided if confirm is not included. (new v1.1.0)
3: Creating, editing, and deleting tasks all rebuild the task in the config. Saving to the config will work properly in the next update and be significantly improved in the next major update. (new v1.1.0, new v2.0.0)

**Comment by LemADEC** [comment]
Reload is always risky for plugins, yours is no exception. Worst case, they shows a reminder after reloading that feature X or Y will need a full server reset.
